apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/name: alertmanager-rules
    app.kubernetes.io/part-of: alertmanager
    app.kubernetes.io/version: main
  name: alertmanager-rules
  namespace: monitoring
spec:
  groups:
  - name: alertmanager.rules
    rules:
    - alert: AlertmanagerFailedReload
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: Configuration has failed to load for {{$labels.instance}}.
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerfailedreload
        summary: Reloading an Alertmanager configuration has failed.
      expr: max_over_time(alertmanager_config_last_reload_successful{job="alertmanager"}[5m])
        == 0
      for: 10m
      labels:
        service: alertmanager
        severity: critical
    - alert: AlertmanagerMembersInconsistent
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: Alertmanager {{$labels.instance}} has only found {{ $value }}
          members of the {{$labels.job}} cluster.
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagermembersinconsistent
        summary: A member of an Alertmanager cluster has not found all other cluster
          members.
      expr: |2-
          max_over_time(alertmanager_cluster_members{job="alertmanager"}[5m])
        < on (job) group_left ()
          count by (job) (max_over_time(alertmanager_cluster_members{job="alertmanager"}[5m]))
      for: 15m
      labels:
        service: alertmanager
        severity: critical
    - alert: AlertmanagerFailedToSendAlerts
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: Alertmanager {{$labels.instance}} failed to send {{ $value |
          humanizePercentage }} of notifications to {{ $labels.integration }}.
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerfailedtosendalerts
        summary: An Alertmanager instance failed to send notifications.
      expr: |2-
            rate(alertmanager_notifications_failed_total{job="alertmanager"}[15m])
          / ignoring (reason) group_left ()
            rate(alertmanager_notifications_total{job="alertmanager"}[15m])
        >
          0.01
      for: 5m
      labels:
        service: alertmanager
        severity: warning
    - alert: AlertmanagerClusterFailedToSendAlerts
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: The minimum notification failure rate to {{ $labels.integration
          }} sent from any instance in the {{$labels.job}} cluster is {{ $value |
          humanizePercentage }}.
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerclusterfailedtosendalerts
        summary: All Alertmanager instances in a cluster failed to send notifications
          to a critical integration.
      expr: |2-
          min by (job, integration) (
              rate(alertmanager_notifications_failed_total{integration=~".*",job="alertmanager"}[15m])
            / ignoring (reason) group_left ()
              rate(alertmanager_notifications_total{integration=~".*",job="alertmanager"}[15m])
          )
        >
          0.01
      for: 5m
      labels:
        service: alertmanager
        severity: critical
    - alert: AlertmanagerClusterFailedToSendAlerts
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: The minimum notification failure rate to {{ $labels.integration
          }} sent from any instance in the {{$labels.job}} cluster is {{ $value |
          humanizePercentage }}.
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerclusterfailedtosendalertsnonCrit
        summary: All Alertmanager instances in a cluster failed to send notifications
          to a non-critical integration.
      expr: |2-
          min by (job, integration) (
              rate(alertmanager_notifications_failed_total{integration!~".*",job="alertmanager"}[15m])
            / ignoring (reason) group_left ()
              rate(alertmanager_notifications_total{integration!~".*",job="alertmanager"}[15m])
          )
        >
          0.01
      for: 5m
      labels:
        service: alertmanager
        severity: warning
    - alert: AlertmanagerConfigInconsistent
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: Alertmanager instances within the {{$labels.job}} cluster have
          different configurations.
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerconfiginconsistent
        summary: Alertmanager instances within the same cluster have different configurations.
      expr: |2-
          count by (job) (count_values by (job) ("config_hash", alertmanager_config_hash{job="alertmanager"}))
        !=
          1
      for: 20m
      labels:
        service: alertmanager
        severity: critical
    - alert: AlertmanagerClusterDown
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: '{{ $value | humanizePercentage }} of Alertmanager instances
          within the {{$labels.job}} cluster have been up for less than half of the
          last 5m.'
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerclusterdown
        summary: Half or more of the Alertmanager instances within the same cluster
          are down.
      expr: |2-
            count by (job) (avg_over_time(up{job="alertmanager"}[5m]) < 0.5)
          /
            count by (job) (up{job="alertmanager"})
        >=
          0.5
      for: 5m
      labels:
        service: alertmanager
        severity: critical
    - alert: AlertmanagerClusterCrashlooping
      annotations:
        dashboard: https://demo.perses.dev/projects/perses/dashboards/alertmanager
        description: '{{ $value | humanizePercentage }} of Alertmanager instances
          within the {{$labels.job}} cluster have restarted at least 5 times in the
          last 10m.'
        runbook: https://github.com/prometheus/alertmanager/blob/main/doc/alertmanager-mixin/README.md#alertmanagerclustercrashlooping
        summary: Half or more of the Alertmanager instances within the same cluster
          are crashlooping.
      expr: |2-
            count by (job) (changes(process_start_time_seconds{job="alertmanager"}[10m]) > 4)
          /
            count by (job) (up{job="alertmanager"})
        >=
          0.5
      for: 5m
      labels:
        service: alertmanager
        severity: critical
